Distance the lower the better
TemporalKGTeam/tkg-framework pull request #2
Opened 2021-02-25 10:44 UTC by maximotus

Now the implementation should fit the assumption that there's a big distance (i.e. a small negative value for the negative samples) between h+r+temp and t of negative samples and vice versa (i.e. a big negative value for the positive samples) a small/zero distance between h+r+temp and t of positive samples.

So the "small negative value for the negative samples" indicates a bigger distance than the "big negative value for the positive samples". That's what we want. Before it was confusing because the bigger values of the positive samples have twisted the distance assumption. 

Of course, this implementation is only used for the distance/translation based models, namely TATransE, TTranse and HyTE. Note that I confused HyTE with ATiSE in the commit messages by accident.

2021-02-25 21:50 UTC, GengyuanMax approved these changes

2021-02-25 21:55 UTC, GengyuanMax requested changes
I think margin loss should not be negated. Also, loss class should be independent of specific model class. When needed, add a new param for this class.

2021-02-25 21:56 UTC, GengyuanMax requested changes
See comments of last commit

2021-02-26 10:13 UTC, maximotus commented
Yes so it's max(0, -|neg|-(-|pos|)+lambda).
So we can write that as max(0, |pos|-|neg|+lambda) I think? (|x| don't mean absolute value in the classical sense but more the unnegated value, so the score before we do torch.neg(x))

Before we had y=1 and so max(0, -1*(|pos|-|neg|)+lambda) = max(0, |neg|-|pos|+lambda).
So we assumed our model will produce high values for pos and low values for neg so we ended getting a low or zero loss for greater pos and getting a big loss for greater neg, right?

So now, we want to turn that logic around? Because the formula of margin ranking loss is now the "opposite" when we negate the scores and let the y be 1 as before. So we now assume that our model will produce low absolute values (= distances) for pos and high absolute values (= distances) for neg.
So we kind of say: "good job, you interpreted the embeddings as you should" if it scores low distances for pos and high distances for neg --> loss=0. And we say "you can do this better, here take this loss for your gradients to make it better next round" if it scores high distances for pos and low distances for neg --> loss>0.

So if we leave it like in my commit, it leads us to the same result as before, that it models positives having big distances and negatives having small ones. But that was exactly the point we wanted to twist around to be consistent with the distance logic.
I see.

2021-02-26 12:40 UTC, GengyuanMax approved these changes

2021-02-26 12:43 UTC, merged